### ISSUE TITLE
質問

### ISSUE THREAD

**Issue by keisuke07** [nama1118/nama1118.github.io#2]
ブランチを切り替えようと思ってcheckoutしてるんですけど、エラーがでます。どうしたら変えられますか？
エラー内容
kei:holidoys_system kei$ git checkout miura/mockup
error: Your local changes to the following files would be overwritten by checkout:
	.DS_Store
Please, commit your changes or stash them before you can switch branches.
Aborting

**Comment by nama1118** [comment]
issueのalertが多すぎて見落としてた…

現在testbranchにいるとして
masterにファイル1があって中身が「hoge」という状態で
testbranchではファイル１の中身が「foo」だと

masterに変えることができない

変えたいなら
・コミットする
・変更内容をリセットする

これをしてからbranch移動かな。あとは禁断のオプション「-f」を使うっていう手もある（強制でbranch移動にする）

**Comment by keisuke07** [comment]
branchの件は片付きました！
今専攻をタブで選べるようにしようと思ってるのですがうまくいきません！
これができればとりあえず完成なのでちょっと手伝ってくれませんか？

**Comment by nama1118** [comment]
OKちょっと見てみます
明日のこともあるからちょっと用意してる

**Comment by keisuke07** [comment]
今pushしておきました！
センターによらないんですよねー

**Comment by nama1118** [comment]
http://nama1118.github.io/

で、見れるようにしてみました

今から確認します。

**Comment by nama1118** [comment]
> 今専攻をタブで選べるようにしようと思ってるのですがうまくいきません！

<img width="368" alt="2015-11-30 22 22 51" src="https://cloud.githubusercontent.com/assets/4418057/11472587/fb8f5b12-97b0-11e5-809c-25731ed8f5a5.png">

登録画面の選考のことですか？

タブってどんなふうにしたいのかな？
http://www.tagindex.com/html_tag/form/select.html

こんな感じ？

**Comment by keisuke07** [comment]
自分のところのブランチに入ってませんか？

**Comment by nama1118** [comment]
多分、コミット取ってこれなかったみたい

**Comment by keisuke07** [comment]
まじっすか！
どうしよう

**Comment by nama1118** [comment]
いやーコミット自体はあるからこっちでmergeしちゃうね

**Comment by keisuke07** [comment]
お願いしまーすっ！

**Comment by nama1118** [comment]
とりあえず見れた。
DS_Storeをignoreしておかないと面倒だ…

**Comment by keisuke07** [comment]
なんか勝手にできるファイルですか？ignoreってなんですか？

**Comment by nama1118** [comment]
簡単に言うとaddされなくなるファイルのことです
個人の環境で値が変わってしまうものは覗いたほうが良いからね

**Comment by keisuke07** [comment]
されなくなるとは？
あとタブのとこがセンターによらないんですけどどうすればいいですかね？

**Comment by nama1118** [comment]
gitの管理の対象から外れるってことです
いくら修正しようがそれはgitで管理しないからaddしてもコミットに反映されないというか
まぁ詳しくはぐぐってくれ

タブは対応した
http://nama1118.github.io/register.html

**Comment by nama1118** [comment]
#7

**Comment by nama1118** [comment]
まぁ、developをpullしてくれればすべての変更が反映されるよ。
もしかしたらコンフリクト起こるかもしれないけど…

明日の都合で、全員のbranchを統合してるから、また明日見直すよ。

**Comment by keisuke07** [comment]
了解です！
